# Generated by Django 4.1.3 on 2023-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('R', 'regular'), ('M', 'Medium'), ('L', 'Large')], default='R', max_length=20),
        ),
    ]
