# Generated by Django 4.1.3 on 2023-01-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='cake',
            new_name='pizza',
        ),
    ]
